# Generated by Django 3.2.25 on 2026-02-20 10:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='creater_by',
            new_name='created_by',
        ),
    ]
